# Generated by Django 2.0.6 on 2018-06-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(verbose_name='Fecha de Inscripción')),
                ('modified_date', models.DateTimeField(verbose_name='Fecha de Última Modificación')),
                ('folio', models.CharField(max_length=8, verbose_name='Número de Folio')),
                ('agreement', models.IntegerField(choices=[(0, 'Particular'), (1, 'SEDESOL'), (2, 'SEBIDESO'), (3, 'DIF'), (4, 'Otro')], default=0, verbose_name='Convenio')),
                ('child_name', models.CharField(max_length=30, verbose_name='Nombre(s)')),
                ('child_familynames', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('child_dob', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('child_curp_id', models.CharField(max_length=30, verbose_name='CURP')),
                ('child_gender', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], default=1, verbose_name='Sexo')),
                ('child_schedule', models.IntegerField(choices=[(0, 'Normal'), (1, 'Asistencial')], default=0, verbose_name='Horario')),
                ('child_group', models.IntegerField(choices=[(0, 'Lactantes'), (1, 'Maternal'), (2, 'Preescolar I'), (3, 'Preescolar II'), (4, 'Preescolar III')], default=2, verbose_name='Grupo')),
                ('child_blood_type', models.IntegerField(choices=[(0, 'O+'), (1, 'O-'), (2, 'A+'), (3, 'A-'), (4, 'AB+'), (5, 'AB-'), (6, 'B+'), (7, 'B-'), (8, 'Langereis+'), (9, 'Langereis-'), (10, 'Junior+'), (11, 'Junior-')], default=0, verbose_name='Tipo de Sangre')),
                ('child_photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Foto')),
                ('child_observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('emergency_telephone_number', models.CharField(blank=True, max_length=15, verbose_name='Número de Emergencia')),
                ('emergency_contact', models.CharField(blank=True, max_length=30, verbose_name='Nombre del Contacto de Emergencia')),
                ('doctor', models.CharField(blank=True, max_length=30, verbose_name='Médico')),
                ('hospital', models.CharField(blank=True, max_length=30, verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'Alumno',
                'ordering': ['child_name', 'child_familynames'],
            },
        ),
        migrations.CreateModel(
            name='ScholarCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=9, verbose_name='Ciclo Escolar')),
            ],
            options={
                'verbose_name': 'Ciclo Escolar',
                'verbose_name_plural': 'Ciclos Escolares',
                'db_table': 'Ciclo Escolar',
                'ordering': ['cycle'],
            },
        ),
        migrations.AddField(
            model_name='alumni',
            name='cycle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.ScholarCycle', verbose_name='Ciclo Escolar'),
        ),
    ]
