# Generated by Django 2.0.6 on 2018-06-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='april_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='april_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Abril'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='april_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='area_colonia',
            field=models.CharField(blank=True, max_length=60, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='august_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='august_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Agosto'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='august_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized1_cell_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono Celular'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized1_familynames',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized1_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre(s) Persona Autorizada'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized1_parentezco',
            field=models.IntegerField(blank=True, choices=[(0, 'Abuelo'), (1, 'Abuela'), (2, 'Tío'), (3, 'Tía'), (4, 'Hermano'), (5, 'Hermana'), (6, 'Primo'), (7, 'Prima'), (8, 'Otro')], null=True, verbose_name='Parentezco'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized1_telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized2_cell_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono Celular'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized2_familynames',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized2_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre(s) Persona Autorizada'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized2_parentezco',
            field=models.IntegerField(blank=True, choices=[(0, 'Abuelo'), (1, 'Abuela'), (2, 'Tío'), (3, 'Tía'), (4, 'Hermano'), (5, 'Hermana'), (6, 'Primo'), (7, 'Prima'), (8, 'Otro')], null=True, verbose_name='Parentezco'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='authorized2_telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='birth_certificate',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Acta de Nacimiento'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='colegiatura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Colegiatura'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='curp_card',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='december_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='december_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Diciembre'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='december_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='events_notes',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='events_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Evento Pagado'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='events_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_cell_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Télefono Celular'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_curp_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Dirección Electrónica'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_familynames',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_ife_file',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Archivo IFE'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_ife_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='IFE'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre(s) Papá'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Archivo Foto'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_telephone_extension',
            field=models.CharField(blank=True, max_length=6, verbose_name='Extensión'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_telephone_work',
            field=models.CharField(blank=True, max_length=15, verbose_name='Télefono Trabajo'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='february_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='february_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Febrero'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='february_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='house_telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de casa'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='immunization_card',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Cartilla de Vacunación'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='insurance_notes',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='insurance_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Seguro Pagado'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='insurance_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='january_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='january_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Enero'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='january_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='june_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='june_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Junio'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='june_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mapa',
            field=models.URLField(blank=True, verbose_name='Mapa'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='march_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='march_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Marzo'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='march_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='may_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='may_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Mayo'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='may_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_cell_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Télefono Celular'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_curp_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Dirección Electrónica'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_familynames',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_ife_file',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Archivo IFE'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_ife_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='IFE'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre(s) Mamá'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Archivo Foto'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_telephone_extension',
            field=models.CharField(blank=True, max_length=6, verbose_name='Extensión'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='mother_telephone_work',
            field=models.CharField(blank=True, max_length=15, verbose_name='Télefono Trabajo'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='november_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='november_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Noviembre'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='november_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='october_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='october_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Octubre'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='october_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='otros_notes',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='otros_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Otros Pagado'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='otros_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='register_notes',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='register_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Inscripción Pagada'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='register_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='september_annotations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='september_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Septiembre'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='september_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='street_exterior_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número Exterior'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='street_interior_number',
            field=models.CharField(blank=True, max_length=5, verbose_name='Número Interior'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='street_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='supplies_notes',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='supplies_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Material Pagado'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='supplies_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='uniform_notes',
            field=models.TextField(blank=True, max_length=400, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='uniform_payed',
            field=models.IntegerField(blank=True, choices=[(0, 'No Pagado'), (1, 'Pagado')], default=0, null=True, verbose_name='Uniforme Pagado'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='uniform_payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción'),
        ),
    ]
