ALUMNI_AGREEMENT_PARTICULAR = 0
ALUMNI_AGREEMENT_SEDESOL = 1
ALUMNI_AGREEMENT_SEBIDESO = 2
ALUMNI_AGREEMENT_DIF = 3
ALUMNI_AGREEMENT_OTHER = 4
ALUMNI_AGREEMENT_CHOICES = (
    (ALUMNI_AGREEMENT_PARTICULAR, 'Particular'),
    (ALUMNI_AGREEMENT_SEDESOL, 'SEDESOL'),
    (ALUMNI_AGREEMENT_SEBIDESO, 'SEBIDESO'),
    (ALUMNI_AGREEMENT_DIF, 'DIF'),
    (ALUMNI_AGREEMENT_OTHER, 'Otro'),
)

ALUMNI_GENDER_MALE = 0
ALUMNI_GENDER_FEMALE = 1
ALUMNI_GENDER_CHOICES = (
    (ALUMNI_GENDER_MALE, 'Masculino'),
    (ALUMNI_GENDER_FEMALE, 'Femenino'),
)

ALUMNI_SCHEDULE_NORMAL = 0
ALUMNI_SCHEDULE_ASSISTANCE = 1
ALUMNI_SCHEDULE_CHOICES = (
    (ALUMNI_SCHEDULE_NORMAL, 'Normal'),
    (ALUMNI_SCHEDULE_ASSISTANCE, 'Asistencial'),
)

ALUMNI_GROUP_UNWEANED = 0
ALUMNI_GROUP_MATERNAL = 1
ALUMNI_GROUP_PRESCHOOL_1 = 2
ALUMNI_GROUP_PRESCHOOL_2 = 3
ALUMNI_GROUP_PRESCHOOL_3 = 4
ALUMNI_GROUP_CHOICES = (
    (ALUMNI_GROUP_UNWEANED, 'Lactantes'),
    (ALUMNI_GROUP_MATERNAL, 'Maternal'),
    (ALUMNI_GROUP_PRESCHOOL_1, 'Preescolar I'),
    (ALUMNI_GROUP_PRESCHOOL_2, 'Preescolar II'),
    (ALUMNI_GROUP_PRESCHOOL_3, 'Preescolar III'),
)

ALUMNI_BLOOD_TYPE_O_POSITIVE = 0
ALUMNI_BLOOD_TYPE_O_NEGATIVE = 1
ALUMNI_BLOOD_TYPE_A_POSITIVE = 2
ALUMNI_BLOOD_TYPE_A_NEGATIVE = 3
ALUMNI_BLOOD_TYPE_AB_POSITIVE = 4
ALUMNI_BLOOD_TYPE_AB_NEGATIVE = 5
ALUMNI_BLOOD_TYPE_B_POSITIVE = 6
ALUMNI_BLOOD_TYPE_B_NEGATIVE = 7
ALUMNI_BLOOD_TYPE_LANGEREIS_POSITIVE = 8
ALUMNI_BLOOD_TYPE_LANGEREIS_NEGATIVE = 9
ALUMNI_BLOOD_TYPE_JUNIOR_POSITIVE = 10
ALUMNI_BLOOD_TYPE_JUNIOR_NEGATIVE = 11
ALUMNI_BLOOD_TYPE_CHOICES = (
    (ALUMNI_BLOOD_TYPE_O_POSITIVE, 'O+'),
    (ALUMNI_BLOOD_TYPE_O_NEGATIVE, 'O-'),
    (ALUMNI_BLOOD_TYPE_A_POSITIVE, 'A+'),
    (ALUMNI_BLOOD_TYPE_A_NEGATIVE, 'A-'),
    (ALUMNI_BLOOD_TYPE_AB_POSITIVE, 'AB+'),
    (ALUMNI_BLOOD_TYPE_AB_NEGATIVE, 'AB-'),
    (ALUMNI_BLOOD_TYPE_B_POSITIVE, 'B+'),
    (ALUMNI_BLOOD_TYPE_B_NEGATIVE, 'B-'),
    (ALUMNI_BLOOD_TYPE_LANGEREIS_POSITIVE, 'Langereis+'),
    (ALUMNI_BLOOD_TYPE_LANGEREIS_NEGATIVE, 'Langereis-'),
    (ALUMNI_BLOOD_TYPE_JUNIOR_POSITIVE, 'Junior+'),
    (ALUMNI_BLOOD_TYPE_JUNIOR_NEGATIVE, 'Junior-'),
)

PARENTEZCO_ABUELO = 0
PARENTEZCO_ABUELA = 1
PARENTEZCO_TIO = 2
PARENTEZCO_TIA = 3
PARENTEZCO_HERMANO = 4
PARENTEZCO_HERMANA = 5
PARENTEZCO_PRIMO = 6
PARENTEZCO_PRIMA = 7
PARENTEZCO_OTRO = 8
PARENTEZCO_CHOICES = (
    (PARENTEZCO_ABUELO, 'Abuelo'),
    (PARENTEZCO_ABUELA, 'Abuela'),
    (PARENTEZCO_TIO, 'Tío'),
    (PARENTEZCO_TIA, 'Tía'),
    (PARENTEZCO_HERMANO, 'Hermano'),
    (PARENTEZCO_HERMANA, 'Hermana'),
    (PARENTEZCO_PRIMO, 'Primo'),
    (PARENTEZCO_PRIMA, 'Prima'),
    (PARENTEZCO_OTRO, 'Otro'),
)

ALUMNI_NOT_PAYED = 0
ALUMNI_PAYED = 1
ALUMNI_CHOICES = (
    (ALUMNI_NOT_PAYED, 'No Pagado'),
    (ALUMNI_PAYED, 'Pagado'),
)

VOICE_CONTACT_TELEPHONE = 0
VOICE_CONTACT_FAX = 1
VOICE_CONTACT_CELLULAR = 2
VOICE_CONTACT_NEXTEL = 3
VOICE_CONTACT_TOLLFREE = 4
VOICE_CONTACT_OTHER = 5
VOICE_CONTACT_CHOICES = (
    (VOICE_CONTACT_TELEPHONE, 'Teléfono'),
    (VOICE_CONTACT_FAX, 'Fax'),
    (VOICE_CONTACT_CELLULAR, 'Celular'),
    (VOICE_CONTACT_NEXTEL, 'Nextel'),
    (VOICE_CONTACT_TOLLFREE, '01 800'),
    (VOICE_CONTACT_OTHER, 'Otro'),
)

VOICE_PLACE_HOME = 0
VOICE_PLACE_WORK = 1
VOICE_PLACE_PERSONAL = 2
VOICE_PLACE_OTHER = 3
VOICE_PLACE_CHOICES = (
    (VOICE_PLACE_HOME, 'Casa'),
    (VOICE_PLACE_WORK, 'Trabajo'),
    (VOICE_PLACE_PERSONAL, 'Personal'),
    (VOICE_PLACE_OTHER, 'Otro'),
)

COLEGIATURA_NORMAL = 0
COLEGIATURA_ASISTENCIAL = 1
COLEGIATURA_OTRO = 2
COLEGIATURA_CHOICES = (
    (COLEGIATURA_NORMAL, 'Normal'),
    (COLEGIATURA_ASISTENCIAL, 'Asistencial'),
    (COLEGIATURA_OTRO, 'Otro'),
)
