""" school register URL Configuration"""
from django.urls import re_path
from .views import (
    AlumniList,
    AlumniRetrieve,
    AlumniRetrievePadres,
    AlumniRetrieveDireccion,
    AlumniRetrieveAutorizado,
    AlumniRetrieveFinanzas,
    AlumniRetrieveDocumentos,
    AlumniRegister,
    AlumniRegisterPadres,
    AlumniRegisterAutorizado,
    AlumniRegisterFinanzas,
    AlumniRegisterDocumentos,
    AlumniUpdate,
    AlumniUpdatePadres,
    AlumniUpdateAutorizado,
    AlumniUpdateFinanzas,
    AlumniUpdateDocumentos,
    AlumniDelete
)

urlpatterns = [
    re_path(
        r'^lista$',
        AlumniList.as_view(),
        name='alumni-list'),
    re_path(
        r'^mostrar/(?P<pk>\d+)$',
        AlumniRetrieve.as_view(),
        name='alumni-show'),
    re_path(
        r'^mostrar/padres/(?P<pk>\d+)$',
        AlumniRetrievePadres.as_view(),
        name='alumni-show-parents'),
    re_path(
        r'^mostrar/direccion/(?P<pk>\d+)$',
        AlumniRetrieveDireccion.as_view(),
        name='alumni-show-address'),
    re_path(
        r'^mostrar/autorizado/(?P<pk>\d+)$',
        AlumniRetrieveAutorizado.as_view(),
        name='alumni-show-authorized'),
    re_path(
        r'^mostrar/finanzas/(?P<pk>\d+)$',
        AlumniRetrieveFinanzas.as_view(),
        name='alumni-show-finances'),
    re_path(
        r'^mostrar/documentos/(?P<pk>\d+)$',
        AlumniRetrieveDocumentos.as_view(),
        name='alumni-show-documents'),
    re_path(
        r'^inscripcion/$',
        AlumniRegister.as_view(),
        name='alumni-register'),
    re_path(
        r'^inscripcion/padres/(?P<pk>\d+)$',
        AlumniRegisterPadres.as_view(),
        name='alumni-register-parents'),
    re_path(
        r'^inscripcion/autorizado/(?P<pk>\d+)$',
        AlumniRegisterAutorizado.as_view(),
        name='alumni-register-authorized'),
    re_path(
        r'^inscripcion/finanzas/(?P<pk>\d+)$',
        AlumniRegisterFinanzas.as_view(),
        name='alumni-register-finances'),
    re_path(
        r'^inscripcion/documentos/(?P<pk>\d+)$',
        AlumniRegisterDocumentos.as_view(),
        name='alumni-register-documents'),
    re_path(
        r'^actualizar/(?P<pk>\d+)$',
        AlumniUpdate.as_view(),
        name='alumni-update'),
    re_path(
        r'^actualizar/padres/(?P<pk>\d+)$',
        AlumniUpdatePadres.as_view(),
        name='alumni-update-parents'),
    re_path(
        r'^actualizar/autorizado/(?P<pk>\d+)$',
        AlumniUpdateAutorizado.as_view(),
        name='alumni-update-authorized'),
    re_path(
        r'^actualizar/finanzas/(?P<pk>\d+)$',
        AlumniUpdateFinanzas.as_view(),
        name='alumni-update-finances'),
    re_path(
        r'^actualizar/documentos/(?P<pk>\d+)$',
        AlumniUpdateDocumentos.as_view(),
        name='alumni-update-documents'),
    re_path(
        r'^borrar/(?P<pk>\d+)$',
        AlumniDelete.as_view(),
        name='alumni-delete'),
]
